# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  bookstoreaspnetangular:
    image: bookstoreaspnetangular
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/obj/
      - /app/bin/
      - /app/out/
